version: '3'
services:
  front:
    container_name: font-no-wait
    build: 
      context: ./NoWait
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "3500:80"
